// ===============================================================
//  這是整個網站唯一需要改的檔案。
//  用「文字編輯」打開，把引號 " " 裡面的字換成你自己的，存檔後
//  重新整理網頁就會看到。
//
//  注意：
//  - 每一行最後的逗號 , 不要刪掉。
//  - 圖片放進 images 資料夾，這裡寫檔名就好，例如 "images/作品1.jpg"。
//  - 不需要的欄位留空 "" 就好。
//  - 作品的標題、年份、圖片是從你的 Behance（behance.net/jialinyang）抓來的。
// ===============================================================

const 網站 = {
  名字: "Yang Jialing",       // 左上角與大標題
  關於我按鈕: "Information",  // 左上方右邊那個連結的文字
  作品按鈕: "Index",          // 右半邊左上角的連結文字（回首頁）

  聯絡: [
    { 名稱: "Behance", 連結: "https://www.behance.net/jialinyang" },
    { 名稱: "Cake", 連結: "https://www.cake.me/zero129380" },
    { 名稱: "LinkedIn", 連結: "https://www.linkedin.com/in/jialin-yang-35a419210/" },
  ],

  // 首頁右邊、大標題下面那一段（例如最新作品或近況）
  近況: {
    標題: "UI/UX Designer",
    副標: "",
    內容: [
      "超過八年 UI/UX 經驗，熟悉 Web 與 App 從研究到上線的完整產品設計流程",
      "作品涵蓋 Web3 數據管理後台、電子支付與品牌 App、形象官網",
    ],
    連到作品: 0,  // 點近況標題要打開哪一件作品（作品清單的編號，從 1 開始；不要就寫 0）
  },

  // ---------- 以下是 Information 頁的內容 ----------
  個人: { 中文名: "楊佳凌", 英文名: "Jialin Yang", 職稱: "UI/UX Designer", 地點: "Taiwan" },

  關於我: [
    "在UI/UX領域，我擁有超過八年的工作經驗，並在Web和移動應用程序的整個產品開發流程中積累了豐富的實戰經驗，涵蓋用戶體驗設計的各個方面。",
    "我曾參與多個專案，包括Web3/區塊鏈產品系統的後台開發、電子支付及品牌相關APP，以及全聯官網和其他各類型專案的形象網站開發。",
    "我具備獨立負責產品設計流程的能力，並能持續跟蹤與優化上線的產品模塊。特別是在與工程團隊的合作中，我始終保持良好的溝通，確保設計與技術的無縫對接，這使我們能夠快速響應用戶需求，並持續提升產品質量。",
  ],

  經歷: [
    { 公司: "自由接案", 職稱: "Freelance UI/UX Designer", 地點: "Remote", 期間: "2025.03–Present", 連結: "" },
    { 公司: "MetaCRM", 職稱: "UI/UX Designer", 地點: "Taipei", 期間: "2023.04–2025.02", 連結: "https://app.metacrm.inc/onboarding" },
    { 公司: "串點移動科技（dotarazzi）", 職稱: "Product Designer", 地點: "Taipei", 期間: "2022.01–2022.12", 連結: "" },
    { 公司: "EY Mtel", 職稱: "UI/UX Designer", 地點: "Taipei", 期間: "2018.12–2021.12", 連結: "" },
    { 公司: "威德數位設計", 職稱: "Website Designer", 地點: "Taipei", 期間: "2016.06–2018.12", 連結: "" },
  ],

  // 內容裡的 [文字](#w4) 會變成連到第 4 件作品的連結；[文字](https://網址) 會變成另開視窗的外部連結；\\n 代表換行
  重點成果: [
    { 標題: "跨產業的後台與 App 專案", 內容: "後台系統：醫院後台、牙醫後台、AI 語音後台。\nApp：企業福委會 App、室內設計網頁版 App。", 出處: "自由接案, 2025–" },
    { 標題: "用 AI 快速做出概念原型（0 到 1）", 內容: "運用 Figma Make 等 Figma AI 功能快速做出原型、驗證概念，專案初期就產出具備基本架構的網頁原型，前期風格溝通與視覺摸索的時間約縮短一半，讓客戶更快確認設計方向。", 出處: "自由接案, 2025–" },
    { 標題: "既有網站的改版與優化（1 到 100）", 內容: "以 html.to.design 將既有網頁導入 Figma，省去重複刻稿的時間，例如某 AI 語音平台後台就是用這個方式持續優化迭代、調整設計；結合 HTML5 / CSS3 基礎與 RWD 佈局邏輯，確保設計稿結構清楚、前端做得出來。", 出處: "自由接案, 2025–" },
    { 標題: "獨立完成從設計到交付", 內容: "從 UI/UX 結構化設計到切版規格交付都獨立完成；在沒有團隊支援下以 AI 工具鏈提高產能，專案皆準時交付。", 出處: "自由接案, 2025–" },
    { 標題: "Web2 / Web3 數據管理後台設計", 內容: "負責分析數據（Analytics）、客群管理（Customer）、行銷策略（Marketing）、客戶服務（Service）四大管理平台的產品流程。", 出處: "MetaCRM, 2023–2025" },
    { 標題: "把鏈上數據變成看得懂的圖表", 內容: "幫助加密項目追蹤鏈上活動，設計有效的商業數據分析圖表。", 出處: "MetaCRM, 2023–2025" },
    { 標題: "上線後持續追蹤優化", 內容: "獨立負責產品設計流程，與工程團隊保持良好溝通，持續優化已上線的產品模塊。", 出處: "MetaCRM, 2023–2025" },
    { 標題: "從零到一打造社群 App", 內容: "獨立負責 [dotarazzi APP](#w4) 從競品分析、發想、Wireframe 到介面設計，涵蓋 iOS & Android。", 出處: "dotarazzi, 2022" },
    { 標題: "讓設計對齊市場與商業目標", 內容: "與 PO、RD 主管討論 App 方向與 UI Flow，並產出 Prototyping 與 UI design guideline。", 出處: "dotarazzi, 2022" },
    { 標題: "獨立規劃 5 個以上 App 專案", 內容: "從需求訪談、易用性測試，到 Wireframe、Flow、版面設計與 Prototype，並建立基礎 Design System。", 出處: "EY Mtel, 2018–2021" },
    { 標題: "電子支付與品牌 App 設計", 內容: "+Pay、POYA Pay、PXPAY、Smart Traveller、Porsche & Pirelli 小程序（[電子支付](#w5)、[Saintpaul](#w11)、[機場服務](#w9)）。", 出處: "EY Mtel, 2018–2021" },
    { 標題: "金融與零售品牌網站", 內容: "法國巴黎人壽產險/壽險線上投保、富蘭克林線上基金、全聯官網（[BNP](#w3)、[全聯](#w13)）。", 出處: "EY Mtel, 2018–2021" },
    { 標題: "行動版活動頁", 內容: "+Pay MGM、PXPAY 印花集點兌換活動。", 出處: "EY Mtel, 2018–2021" },
    { 標題: "用研究支撐設計決策", 內容: "透過競品分析、User persona、User Test 與眼動儀測試數據取得使用者洞見，轉化為設計策略與功能，減少使用者流失。", 出處: "EY Mtel, 2018–2021" },
    { 標題: "購物網站與形象網站設計", 內容: "負責不同專案型態的購物網站、形象網站，如[東元家電網站](#w14)，與客戶、前後端工程師討論各項需求。", 出處: "威德數位設計, 2016–2018" },
  ],

  技能: [
    { 標題: "使用者研究", 內容: "需求訪談 / 競品分析 / User Persona / 易用性測試 / 眼動儀測試數據" },
    { 標題: "流程與架構", 內容: "Sitemap / Wireframe / UI Flow / Prototyping" },
    { 標題: "介面設計", 內容: "iOS & Android App / Web / 數據管理後台 / Design Guidelines / Design System" },
    { 標題: "AI 輔助設計", 內容: "Figma Make / html.to.design / 快速原型製作（Rapid Prototyping）" },
    { 標題: "跨團隊協作", 內容: "與 PO、RD、客戶討論需求與架構 / 上線產品的追蹤與優化" },
    { 標題: "工具", 內容: "Figma, Figma Make, html.to.design, Sketch, Zeplin, Illustrator, Photoshop" },
  ],

  學歷: [
    { 學校: "國立雲林科技大學", 科系: "視覺傳達設計系", 期間: "2009–2013" },
  ],
  // ---------- Information 頁到這裡 ----------

  地址: ["Yang Jialing", "UI/UX Designer", "Taipei, Taiwan"],  // 頁尾中間，一個引號一行
  頁尾左下: "Colophon",                                      // 頁尾左下的小字

  // 封面：左邊的小圖；圖片：點開後右邊顯示的大圖（可以放很多張）
  作品: [
    {
      標題: "Dashboard_web3",
      副標: "",
      年份: "2025",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/224813375/Dashboard_web3" } ],
      封面: "images/01-dashboard-web3-cover.jpg",
      圖片: ["images/01-dashboard-web3.jpg"],
    },
    {
      標題: "Sign in Flow",
      副標: "",
      年份: "2025",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/219595279/Sign-in-Flow" } ],
      封面: "images/02-sign-in-flow-cover.jpg",
      圖片: ["images/02-sign-in-flow.jpg"],
    },
    {
      標題: "BNP Banking Design",
      副標: "",
      年份: "2023",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/164901581/BNP-Banking-Design" } ],
      封面: "images/03-bnp-banking-design-cover.jpg",
      圖片: ["images/03-bnp-banking-design.jpg"],
    },
    {
      標題: "Social Media App",
      副標: "",
      年份: "2023",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/160509861/Social-Media-App" } ],
      封面: "images/04-social-media-app-cover.png",
      圖片: ["images/04-social-media-app.jpg"],
    },
    {
      標題: "Electronic Payment APP / uiux design",
      副標: "",
      年份: "2021",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/120584693/Electronic-Payment-APP-uiux-design" } ],
      封面: "images/05-electronic-payment-app-uiux-design-cover.jpg",
      圖片: ["images/05-electronic-payment-app-uiux-design.jpg"],
    },
    {
      標題: "Game ux/ui design",
      副標: "",
      年份: "2021",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/120572001/Game-uxui-design" } ],
      封面: "images/06-game-uxui-design-cover.png",
      圖片: ["images/06-game-uxui-design.jpg"],
    },
    {
      標題: "PX PAY Activity_印花兌換活動 UIUX",
      副標: "",
      年份: "2021",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/118010391/PX-PAY-Activity_-UIUX" } ],
      封面: "images/07-px-pay-activity-uiux-cover.png",
      圖片: ["images/07-px-pay-activity-uiux.jpg"],
    },
    {
      標題: "POYA PAY APP / UI Design",
      副標: "",
      年份: "2021",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/118006243/POYA-PAY-APP-UI-Design" } ],
      封面: "images/08-poya-pay-app-ui-design-cover.png",
      圖片: ["images/08-poya-pay-app-ui-design.jpg"],
    },
    {
      標題: "smart traveler app",
      副標: "",
      年份: "2021",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/117845841/smart-traveler-app" } ],
      封面: "images/09-smart-traveler-app-cover.png",
      圖片: ["images/09-smart-traveler-app.jpg"],
    },
    {
      標題: "Pirelli_App",
      副標: "",
      年份: "2020",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/98872755/Pirelli_App" } ],
      封面: "images/10-pirelli-app-cover.png",
      圖片: ["images/10-pirelli-app.jpg"],
    },
    {
      標題: "Saintpaul_App",
      副標: "",
      年份: "2020",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/98744811/Saintpaul_App" } ],
      封面: "images/11-saintpaul-app-cover.png",
      圖片: ["images/11-saintpaul-app.jpg"],
    },
    {
      標題: "Porsche＿App",
      副標: "",
      年份: "2020",
      媒材: "UI/UX Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/98724087/PorscheApp" } ],
      封面: "images/12-porscheapp-cover.png",
      圖片: ["images/12-porscheapp.jpg"],
    },
    {
      標題: "pxmart_web",
      副標: "",
      年份: "2020",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/98933131/pxmart_web" } ],
      封面: "images/13-pxmart-web-cover.jpg",
      圖片: ["images/13-pxmart-web.jpg"],
    },
    {
      標題: "TECO home web",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58601133/TECO-home-web" } ],
      封面: "images/14-teco-home-web-cover.jpg",
      圖片: ["images/14-teco-home-web.jpg"],
    },
    {
      標題: "Huangshan Stone Porcelain Tiles",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58605767/Huangshan-Stone-Porcelain-Tiles" } ],
      封面: "images/15-huangshan-stone-porcelain-tiles-cover.jpg",
      圖片: ["images/15-huangshan-stone-porcelain-tiles.jpg"],
    },
    {
      標題: "HuawLon cotton material website",
      副標: "",
      年份: "2018",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/71951975/HuawLon-cotton-material-website" } ],
      封面: "images/16-huawlon-cotton-material-website-cover.jpg",
      圖片: ["images/16-huawlon-cotton-material-website.jpg"],
    },
    {
      標題: "Grand HI-LAI Hotel",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606125/Grand-HI-LAI-Hotel" } ],
      封面: "images/17-grand-hi-lai-hotel-cover.jpg",
      圖片: ["images/17-grand-hi-lai-hotel.jpg"],
    },
    {
      標題: "NEXT Design Group",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606271/NEXT-Design-Group" } ],
      封面: "images/18-next-design-group-cover.jpg",
      圖片: ["images/18-next-design-group.jpg"],
    },
    {
      標題: "DJ drums",
      副標: "",
      年份: "2018",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/71948777/DJ-drums" } ],
      封面: "images/19-dj-drums-cover.jpg",
      圖片: ["images/19-dj-drums.jpg"],
    },
    {
      標題: "Deryi Kitchenware",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58605925/Deryi-Kitchenware" } ],
      封面: "images/20-deryi-kitchenware-cover.jpg",
      圖片: ["images/20-deryi-kitchenware.jpg"],
    },
    {
      標題: "AbGenomics Biotechnology company",
      副標: "",
      年份: "2018",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/71949573/AbGenomics-Biotechnology-company" } ],
      封面: "images/21-abgenomics-biotechnology-company-cover.jpg",
      圖片: ["images/21-abgenomics-biotechnology-company.jpg"],
    },
    {
      標題: "HuawLon proposal",
      副標: "",
      年份: "2018",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/71948929/HuawLon-proposal" } ],
      封面: "images/22-huawlon-proposal-cover.jpg",
      圖片: ["images/22-huawlon-proposal.jpg"],
    },
    {
      標題: "JustSleep Hotel",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606423/JustSleep-Hotel" } ],
      封面: "images/23-justsleep-hotel-cover.jpg",
      圖片: ["images/23-justsleep-hotel.jpg"],
    },
    {
      標題: "AURO Paint",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606631/AURO-Paint" } ],
      封面: "images/24-auro-paint-cover.jpg",
      圖片: ["images/24-auro-paint.jpg"],
    },
    {
      標題: "Pan Asia Engineering",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606567/Pan-Asia-Engineering" } ],
      封面: "images/26-pan-asia-engineering-cover.jpg",
      圖片: ["images/26-pan-asia-engineering.jpg"],
    },
    {
      標題: "TECO Electrical & Mechanical",
      副標: "",
      年份: "2017",
      媒材: "Web Design",
      說明: "",
      補充: "",
      連結: [ { 名稱: "在 Behance 上看", 連結: "https://www.behance.net/gallery/58606341/TECO-Electrical-Mechanical" } ],
      封面: "images/27-teco-electrical-mechanical-cover.jpg",
      圖片: ["images/27-teco-electrical-mechanical.jpg"],
    },
  ],
};
